{
	"_Type": "Action.Type.Filter",
	"ActionResult": {
		"_Name": "NavToFiltrosViaje"
	},
	"Filterable": "#Page:ListaViajes/#Control:SectionedTable0",
	"PageToOpen": "/Viajes/Pages/FiltrosViajes.page"
}