{
	"_Type": "Action.Type.ToastMessage",
	"ActionResult": {
		"_Name": "ErrorInicializarStorage"
	},
	"Message": "Ocurrió un error al inicializar el modo offline: {#ActionResults:InicializarStorage/error}"
}