{
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "SubirCambios"
	},
	"OnSuccess": "/Viajes/Actions/Offline/LimpiarStorage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Guardando cambios...",
	"Service": "/Viajes/Services/VIAJES.service"
}